#!/usr/bin/env ruby
# frozen_string_literal: true

if File.directory?("#{__dir__}/../lib")
  $LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
end

require "inquirex/tty"

Dry::CLI.new(Inquirex::TTY::Commands).call
